name: Robot Framework CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create results and allure directories
        run: |
          mkdir -p results
          mkdir -p allure-results

      - name: Install Allure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jre
          curl -o allure.tgz -L https://github.com/allure-framework/allure2/releases/download/2.24.0/allure-2.24.0.tgz
          tar -zxf allure.tgz
          sudo mv allure-2.24.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure
          allure --version

      - name: Run Robot Framework Tests
        run: |
          robot --variable HEADLESS:true --listener "allure_robotframework:./allure-results" -d results tests/ui
        env:
          CI: true

      - name: Debug Allure Results
        if: always()
        run: |
          echo "Checking allure-results directory:"
          ls -la allure-results/ || echo "allure-results directory does not exist"
          echo "File count:"
          find allure-results -name "*.json" | wc -l || echo "No JSON files found"
          echo "Sample files:"
          ls allure-results/ | head -5

      - name: Generate Allure HTML Report
        if: always()
        run: |
          if [ -d "allure-results" ] && [ "$(ls -A allure-results 2>/dev/null)" ]; then
            echo "Generating Allure report..."
            allure generate allure-results --clean -o allure-report
            echo "Allure report generated successfully"
            echo "Report contents:"
            ls -la allure-report/
          else
            echo "No allure-results found or directory is empty"
            echo "Creating empty report for debugging"
            mkdir -p allure-report
            echo "<html><body><h1>No test results found</h1></body></html>" > allure-report/index.html
          fi

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: robot-results
          path: results/

      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results
          path: allure-results/

      - name: Upload Allure HTML Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-html-report
          path: allure-report/
